django_test/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('users.urls', 'users'), namespace='users'))
] + static(settings.STATIC_URL)

users/urls.py
from django.conf.urls import url
from users import views

urlpatterns = [
    url(r'^$', views.UserList.as_view(), name='user-list'),
    url(r'^user/create/$', views.UserCreate.as_view(), name='create-user'),
    url(r'^user/(?P<pk>\d+)/edit/$', views.UserUpdate.as_view(), name='user-edit'),
    url(r'^user/(?P<pk>\d+)/remove/$', views.UserRemove.as_view(), name='remove-user'),
    url(r'^user/(?P<pk>\d+)/$', views.UserDetail.as_view(), name='user-detail'),
    url(r'^user/export_csv/$', views.export_users_csv, name='export-users-csv'),
]

users/models.py
import random

from django.urls import reverse
from django.db import models


# extending User model
from django.contrib.auth.models import AbstractUser


class MyUser(AbstractUser):
    random_number = models.IntegerField(default=round(random.random() * 100))
    birthday = models.DateField(null=True)

    def get_absolute_url(self):
        return reverse('users:user-list')

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.contrib.auth import get_user_model

# get extended User model
User = get_user_model()


class UserList(ListView):
    template_name = 'users_templates/user_list.html'
    model = User


class UserDetail(DetailView):
    template_name = 'users_templates/user_detail.html'
    model = User


class UserCreate(CreateView):
    template_name = 'users_templates/user_create.html'
    model = User
    fields = ['username', 'email', 'first_name', 'last_name', 'is_active', 'is_staff', 'is_superuser', 'birthday']


class UserRemove(DeleteView):
    model = User
    success_url = reverse_lazy('users:user-list')


class UserUpdate(UpdateView):
    model = User
    template_name = 'users_templates/user_edit.html'
    fields = ('username', 'email', 'first_name', 'last_name', 'is_active', 'is_staff', 'is_superuser', 'birthday')


import csv

from django.http import HttpResponse


def export_users_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="users.csv"'

    writer = csv.writer(response)
    writer.writerow(['Username', 'Birthday', 'Email address', 'Random Number'])

    users = User.objects.all().values_list('username', 'birthday', 'email', 'random_number')
    for user in users:
        writer.writerow(user)

    return response

templates/base/_base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}

  <head>

    <meta charset="UTF-8">
    <title>Test</title>
    <link rel="stylesheet" href="{% static 'styles/css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

  </head>

  <body>
    <div class="main-wrapper">
      {% block main %}{% endblock %}
    </div>
  </body>

</html>

users/templates/users_templates/user_create.html
{% extends 'base/_base.html' %}

{% block main %}

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <a href="{% url 'users:user-list' %}">
      <button type="button" class="btn btn-sm btn-info">Back</button>
    </a>
    <button type="submit" class="btn btn-sm btn-primary">Create</button>
  </form>

{% endblock %}

users/templates/users_templates/user_detail.html
{% extends 'base/_base.html' %}

{% block main %}

  <form action="{% url 'users:remove-user' object.pk %}" method="post" class="create-user-form">
    {% csrf_token %}
    <p>
      <label for="id_username">Username:</label> <span class="helptext">{{ object.username }}</span>
    </p>
    <p>
      <label for="id_first_name">First name:</label> <span class="helptext">{{ object.first_name }}</span>
    </p>
    <p>
      <label for="id_last_name">Last name:</label> <span class="helptext">{{ object.last_name }}</span>
    </p>
    <p>
      <label for="id_email">Email address:</label> <span class="helptext">{{ object.email }}</span>
    </p>
    <p>
      <label for="id_is_active">Active:</label> <span class="helptext">{{ object.is_active }}</span>
    </p>
    <p>
      <label for="id_is_staff">Staff status:</label> <span class="helptext">{{ object.is_staff }}</span>
    </p>
    <p>
      <label for="id_is_superuser">Superuser status:</label> <span class="helptext">{{ object.is_superuser }}</span>
    </p>
    <p>
      <label for="id_random_number">Random number:</label> <span class="helptext">{{ object.random_number }}</span>
    </p>

    <a href="{% url 'users:user-list' %}">Back To Home</a>
    <button type="submit" class="btn btn-sm btn-danger">Remove</button>
  </form>

{% endblock %}

users/templates/users_templates/user_edit.html
{% extends 'base/_base.html' %}

{% block main %}
  <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <a href="{% url 'users:user-list' %}">Back</a>
      <button type="submit">Save Changes</button>
  </form>
{% endblock %}

users/templates/users_templates/user_list.html
{% extends 'base/_base.html' %}

{% load BizzFuzz is_allowed from user_templatetags %}

{% block main %}
  <p>
    <a href="{% url 'users:create-user' %}">
      <button type="button" class="btn btn-sm btn-info">CREATE USER</button>
    </a>
  </p>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>User Name</th>
        <th>Birthday</th>
        <th>Eligible</th>
        <th>Random Number</th>
        <th>Bizz Fuzz</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for user in object_list %}
      <tr>
        <td>{{ user.username }}</td>
        <td>{{ user.birthday }}</td>
        <td>{% is_allowed user.birthday %}</td>
        <td>{{ user.random_number }}</td>
        <td>{% BizzFuzz user.random_number %}</td>
        <td>
          <a href="{% url 'users:user-detail' user.pk %}">Details</a>
          <a href="{% url 'users:user-edit' user.pk %}">Edit</a>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'users:export-users-csv' %}">
    <button type="button" class="btn btn-sm btn-info">Download List In CSV</button>
  </a>

{% endblock %}